In [23]:
n = 2
A = [[7, 8], [2 , 9]]
B = [[14, 5], [5, 18]]
C = [[0,0],[0,0]]

#Output: 
#C = [[138, 179], [73, 172]]

result = [[0,0], 
          [0,0]] 
   
# iterate through rows 
for i in range(n):    
    for j in range(n): 
        result[i][j] = A[i][j] * B[i][j]
        

for x in result: 
    print(x)

[98, 40]
[10, 162]


In [4]:
n = 2
D = [[0 for x in range(n)] for x in range(n)]
D[0][0] = 1
D[0][1] = 2
D

[[1, 2], [0, 0]]

In [25]:
#Program to multiply two matrices using nested loops
 
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix   
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
 
# iterating by row of A
for i in range(len(A)):
 
    # iterating by column by B
    for j in range(len(B[0])):
 
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]


for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]

In [26]:
import numpy as np
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
 
# result will be 3x4
 
result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]
 
result = np.dot(A,B)
 
for r in result:
    print(r)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]
